### ISSUE TITLE
Feature request: use the correct case when displaying the names of instructions

### ISSUE THREAD

**Issue by socketpair** [perliedman/leaflet-routing-machine#120]
From https://github.com/Project-OSRM/osrm-backend/issues/1488 :

Unfortunatelly, in other languages, correct translation of (for example) `Turn left onto NAME` requires some transformations on `NAME` (change forms of the words in `NAME`). Without that, instructions are not looking good.

I will try to explain using mix of languages. Instead of `Turn left onto Уральская улица` it should be `Turn left onto УральскУЮ улицУ`. (I highlated changes using caps-lock).

i.e. instead of `Поверните налево на Уральская улица` it should be `Поверните налево на Уральскую улицу`.

Seems http://nlp.lsi.upc.edu/freeling/ or another Natural Language Processing libraries can help for that problem.

It will be nice if you can handle that in routing instructions. AFAIK no one implement that.

**Comment by perliedman** [comment]
Since I want to keep Leaflet Routing Machine free from more dependencies, and this seems like a bit specific, I'd recommend creating a custom [`L.Routing.Formatter`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-formatter) - by overriding the `formatInstruction`, you can easily fix this.

I guess it would be nice if you could publish such a change here on GitHub, since it sounds like something others could use as well - keep me posted if you do, so that I can link to it from the LRM site.
