### ISSUE TITLE
Getting line bounds

### ISSUE THREAD

**Issue by Polymathronic** [perliedman/leaflet-routing-machine#122]
I am trying to make the map fit the line bounds by:
```javascript
var line = L.Routing.line(route);
map.fitBounds(line.getBounds());
```
but to no avail, as `this._route.inputWaypoints` in `_findWaypointIndices()` seems to be undefined. Am I doing something wrong, or is it a bug?

**Comment by perliedman** [comment]
Where did you get the `route` instance from? When returned from for example `L.Routing.OSRM`, it should have the `inputWaypoints` property set.

If you're constructing the `route` instance yourself, make sure to fill it with the waypoints of the route.

**Comment by Polymathronic** [comment]
```javascript
route = L.Routing.control({
  waypoints: [
	userLocation,
	goalLocation
  ],
  serviceUrl: 'http://router.project-osrm.org/viaroute',
  lineOptions: {
	styles: [{color: '#19afc3', opacity: 0.8, weight: 9},
	{color: '#00ffb4', opacity: 0.8, weight: 6},
	{color: '#00fdf6', opacity: 1, weight: 2}],
	addWaypoints: true
  }
});

route.addTo(map);
```

That part works fine, but I still can't get the bounds.

**Comment by perliedman** [comment]
That's weird, the control uses more or less the same code to fit the bounds, so that should definitely work: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Control.js#L104

If you can provide example code, ideally using jsfiddle or similar, it would help tracking down the problem.

**Comment by Polymathronic** [comment]
Try this: http://jsfiddle.net/eqwscwym/ (please check the console error log)
Thanks.

**Comment by perliedman** [comment]
Alright! The constructor for `L.Routing.Line` expects an [`IRoute`](http://www.liedman.net/leaflet-routing-machine/api/#iroute) instance to be passed to it, not an instance of the control. That is, it needs an actual route.

Due to JavaScript being asynchronous, you can't get the route directly after the control is created - at that point, the routing result has not yet been returned from the server.

Reacting on when the result is returned from the server is what events are used for, you can do:

```
var route = L.Routing.control({ ... });

route.on('routeselected', function(r) {
    var line = L.Routing.line(r);
    var bounds = line.getBounds();
    map.fitBounds(bounds);
});
```

Finally, note that what you're doing here, fitting the map to the current route line, is already built in to the control: set the option `fitSelectedRoutes` to `true`, and it will do it for you (the default is to use the `"smart"`fitting option, which usually works even better).

**Comment by Polymathronic** [comment]
Thanks for the tip. `fitSelectedRoutes` did the trick. However, even if I try to instantiate the line *after* the control is created, I get the same error: http://jsfiddle.net/eqwscwym/1/

**Comment by perliedman** [comment]
Yes, sorry, my error typing the code too fast.

You should add the event handler like this:

```js
route.on('routeselected', function(e) {
    var r = e.route;
    var line = L.Routing.line(r);
    var bounds = line.getBounds();
    map.fitBounds(bounds);
});
```
