### ISSUE TITLE
Itinerary / driving directions container

### ISSUE THREAD

**Issue by Polymathronic** [perliedman/leaflet-routing-machine#123]
Any way LRM could print out the driving directions elsewhere, i.e. in a different container? `containerClassName` only adds the specified class to the default container (`leaflet-routing-container`).

**Comment by perliedman** [comment]
Absolutely, but not completely built in to the plugin, since there's many ways to do it.

You can hook in to the control's `routeselected` event, and there you will get the selected route's `instructions`. You can use [`L.Routing.Formatter`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-formatter) to format to instructions, or do it yourself, and put the result in any container you want.

Hope this helps!
