### ISSUE TITLE
Is there a way with this to route within seperate leaflet clusters?

### ISSUE THREAD

**Issue by mikeohara** [perliedman/leaflet-routing-machine#129]
This may seem odd, but what If I wanted to have several clusters on one map, and each one would be routed when one drilled down. (the clusters would not be routed to each other, however)

**Comment by perliedman** [comment]
Not entirely sure what you mean by "each one would be routed when drilled down"? Can you elaborate on what you mean by routing within a cluster?

I assume by cluster, you mean like a set of points/markers that have been clustered by Leaflet Marker Cluster or similar?

**Comment by mikeohara** [comment]
That is correct. Clustered points via Leaflet Marker Cluster.

**Comment by perliedman** [comment]
Ok... so what route do you want to generate when a cluster is selected/drilled down? A route between all the members of that cluster?

**Comment by perliedman** [comment]
Closing since no new info has been added for a while.

Feel free to post more info and I'll consider re-opening.

**Comment by mikeohara** [comment]
Hi sorry: Yes, when a cluster or unique grouping of points on a map, and route between them exclusively.

**Comment by perliedman** [comment]
Ok, since there might be more than two points in the cluster, the order to visit all of them must first be determined, right?

Finding the optimal order of the waypoints boils down to the travelling salesman's problem (TSP), which is outside the scope of Leaflet Routing Machine.

I've looked at using [jsprit](https://github.com/jsprit/jsprit) for such, and other more advanced planning problems. You might find it interesting (and you can still use OSRM or GraphHopper to calculate the resulting routes and distances).
