### ISSUE TITLE
Access route coordinates

### ISSUE THREAD

**Issue by StephanGeorg** [perliedman/leaflet-routing-machine#131]
Is there a method that returns the coordinates of the route? Or do I have to access them directly with 
x._line._route.coordinates.

**Comment by perliedman** [comment]
The key here is to use events to get hold of the route. There's a couple of different events, but usually `routeselected` is the one you want - each time a new route is displayed, this event will fire. If you add a listener, you will get the route object and can do whatever you want with coordinates and other information.

For example:

```javascript
var control = L.Routing.control({ ... })
    .on('routeselected', function(e) {
        var route = e.route;
        for (var i = 0; i < route.coordinates.length; i++) {
            // Do something interesting here
        }
    });
```

In my experience, once you get used to events, it's a much more natural way to code in JavaScript, since it takes away a lot of the challenge of asynchronous programming. For example, `x._line` will often be `null`/`undefined`, and you will have to add a lot of checks to see when it changes. Not to mention that member variables starting with `_` are to be considered "private", and might change in future versions, since they're not part of the API.

Check the [Leaflet Routing Machine API](http://www.liedman.net/leaflet-routing-machine/api/) for more info on events and other things, if you haven't already.

**Comment by StephanGeorg** [comment]
Thank's for the hint @perliedman .
