### ISSUE TITLE
Access server response

### ISSUE THREAD

**Issue by matbeard** [perliedman/leaflet-routing-machine#146]
Thanks for this brilliant plugin and for helping out with my previous issue (working now).

Can you let me know if it's possible to access the response from the routing server?

I'd particularly like to access the legs array of a Valhalla response.

Thanks again

**Comment by perliedman** [comment]
The `IRouter`'s purpose is to give a unified interface to multiple backends, so that the rest of Leaflet Routing Machine can work without caring about the response format of each backend.

That means that the `IRoute` resulting from a query does _not_ contain information specific to the routing backend. If you need the backend's data directly for reason, you are probably better off just querying it directly.

Any info in particular that you need out of Valhalla that isn't already in the `IRoute` you get from LRM?

**Comment by matbeard** [comment]
Yes, I'm routing via a waypoint -- the response from Valhalla provides a summary for each leg of the route, not just a summary for the complete route.

It's not a major issue -- I just have to use separate calls for each leg.

Thanks

**Comment by boldtrn** [comment]
@matbeard You could write your own `Router` that extends the Valhalla router. Should be quite straight forward.

**Comment by perliedman** [comment]
Yes, I agree with @boldtrn, extending the router class is a good practice if you need to add additional information.
