### ISSUE TITLE
custom markers

### ISSUE THREAD

**Issue by Doeran** [perliedman/leaflet-routing-machine#149]
Hello and thank you for your job.
How do I add custom markers, wherein the first marker should be different from the rest.
thanks a lot.

**Comment by perliedman** [comment]
Hi, great that you find it useful!

There is an option, `createMarker`, that you can use for this. You can pass a function, that should take the waypoint index, the waypoint itself and the total number of waypoints as argument, and return the marker for the waypoint.

As an example, the default implementation looks like this:

```
			createMarker: function(i, wp, nWaypoints) {
				var options = {
						draggable: this.draggableWaypoints
					},
				    marker = L.marker(wp.latLng, options);

				return marker;
			},
```

If you haven't already, there's plenty of API docs here: http://www.liedman.net/leaflet-routing-machine/api/

**Comment by logicguy1** [comment]
@perliedman How do we set a custom marker image? When i try #407 all my markers are missing due to invalid options (from what i could see in the API). I also cant seem to find much documentation on the marker icons themsevles nor the avaliable options for the markers. Have you documented these somewhere yet?

**Comment by curtisy1** [comment]
Please open another issue if you have a question, or alternatively ask on StackOverflow (note, I'm not as active there as I have yet to figure out notification settings).

As for your question, I created a [working fiddle](https://codepen.io/curtisy1/pen/XWVzovy) a while ago that shows you how to use the createMarker function Per mentioned.
Since you'll want to instantiate a Leaflet marker, its options can be found in the [Leaflet docs](https://leafletjs.com/reference.html#marker)
