### ISSUE TITLE
Strange route is being generated

### ISSUE THREAD

**Issue by SamSalman** [perliedman/leaflet-routing-machine#164]
Hello,

LRM generating totally wrong route, please see the attached screenshots:

![screenshot from 2015-09-22 10 33 20](https://cloud.githubusercontent.com/assets/3371099/10013036/63f52898-6116-11e5-9436-eb4f52f17335.png)
![screenshot from 2015-09-22 10 33 03](https://cloud.githubusercontent.com/assets/3371099/10013037/63f6711c-6116-11e5-848a-d3d6c6d2aee0.png)

It jumped to somewhere in Poland however all gives coordinates are from Finland.

Update:
Just tested in OSRM project website and its also generating wrong route by given coordinates.

Thank you in advance.

**Comment by perliedman** [comment]
Yeah, this is not an issue in LRM. The problem is probably in the OSM data, making it impossible to get from that island without using a weird ferry (just a guess from a very quick look).

If you feel this is not a data issue, but a software problem, you should report it to OSRM, which does the actual route calculation.

A link to the actual route and/or waypoint locations would be good to track this down.

**Comment by SamSalman** [comment]
I already reported it in OSRM, I also mentioned the waypoint of the locations in it. Here is the link to the report: https://github.com/Project-OSRM/osrm-backend/issues/1700#issuecomment-142209396
But still haven't got any useful solution of that.
