### ISSUE TITLE
Disable itinerary completely

### ISSUE THREAD

**Issue by web2style** [perliedman/leaflet-routing-machine#177]
Is there a way not to render itinerary at all? The only way to do it I found is to hide it with `show: false`. But this isn't the best way if I have to render this block manually.

**Comment by perliedman** [comment]
Currently, not if you're using `L.Routing.Control`, since it inherits of `L.Routing.Itinerary`, and in essence _is_ an itinerary.

Note that it's possible to write your own control, the control class itself isn't that much code.

In the future, it would be interesting to make this less coupled, for example for scenarios like what you're describing, but it would require some refactoring, and also some thought to keep the API easy to use for the most common scenarios.
