### ISSUE TITLE
cdn support

### ISSUE THREAD

**Issue by hanbyul-here** [perliedman/leaflet-routing-machine#192]
Any plan to get leafelt-roting-machine on cdn? maybe using [cdnjs](https://github.com/cdnjs/cdnjs) ? I think there are plenty of people who can get benefit from this.

**Comment by perliedman** [comment]
In principle, this sounds like a good idea.

Having looked at the cdnjs docs, I found them long and confusing, to be honest. Since my time for LRM and other spare time projects is pretty limited, this probably will not be on the top of my todo.

If it can be done with minimum hassle, automated for future releases and/or handled by someone else, I'm open to suggestions!

**Comment by Kcchouette** [comment]
I haven't see this issue until today. I just add it on jsDelivr, a free open-source CDN: https://github.com/jsdelivr/jsdelivr/pull/8896; but it takes the last version with the biggest number, here ```3.0.0-beta.1``` is only available. Normally the bot auto-update the files and add it if version > ```3.0.0-beta.1```.

You can add the oldest version with the [advanced method](https://github.com/jsdelivr/jsdelivr/blob/contributing-md/CONTRIBUTING.md#advanced).

**Comment by perliedman** [comment]
Thanks! This looks promising, without knowing anything about jsDelivr.

Should probably use npm as package manager and not bower, since I don't personally use Bower - it has happened before, and will likely happen again, that I break the Bower dist somehow.

**Comment by Kcchouette** [comment]
Ok, do not hesitate to PR to modify the file ```update.json``` to be up to date with what you want :)

**Comment by perliedman** [comment]
LRM is now also available from CDNJS: https://cdnjs.com/libraries/leaflet-routing-machine.

**Comment by hanbyul-here** [comment]
Thanks a lot!!!
