### ISSUE TITLE
Comprehensive object excluding itenerary

### ISSUE THREAD

**Issue by umacys** [perliedman/leaflet-routing-machine#221]
Hi,

To my understanding, this plugin introduces two main functionalities on Leaflet. First, to display a line and waypoints (as markers) which represent a formal route in terms of UX. Second, display a directions of the displayed route. Control is a master class for both functionalities. Line and Plan objects are used for drawing a line and waypoints.

Suppose, user does not need the itinerary, and has multiple routes (both line and markers) to display. Some of these route layers are required to be shown/hidden. Is there any master class extending Layer/LayerGroup to represent route without itenerary? I believe, such a class would save time for implementation.

Thanks in advance.

**Comment by perliedman** [comment]
In version 2, it's a bit messy to do what you want, I think you would need to use the router class directly (for example `L.Routing.OSRM`) and use the results from the `route` method to create `L.Routing.Line` layers which display the lines. You would probably also want to add waypoint markers manually (just using L.Marker or whatever). Doing it that way, you will lose the UI to edit the route, though, since it's in the control.

You can also try to just hide the itinerary, it's pretty straight forward to do with CSS.

In the coming version 3, from the `develop` branch, things are split apart in a clearer way, but it's still WIP, but you can of course try it. For example, the control itself can be created without an itinerary component and without a geocoder component, and it will not show the "sidebar", just the line and the waypoints, much as you like.
