### ISSUE TITLE
localized default labels for roads without names

### ISSUE THREAD

**Issue by phibo23** [perliedman/leaflet-routing-machine#241]
I use the plugin for bike and foot routing and some of the roads in results don't have names so that the instructions look like this:

![bildschirmfoto 2016-05-11 um 17 23 19](https://cloud.githubusercontent.com/assets/1328782/15186377/1b977982-179d-11e6-8e4d-0b62e0c901dc.png)

Is there an existing mechanism to pass each road value through a formatter before being inserted into the instructions template? 
https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Localization.js

**Comment by perliedman** [comment]
The best way is to adapt your OSRM profile instead, so that it doesn't spit out useless names. At least that is what I've done in [my bike router](https://github.com/perliedman/cykelbanor/blob/gh-pages/config/bicycle5.lua).

You can also override `L.Routing.Formatter`, or make your own subclass of `L.Routing.OSRM`, to override how instructions are created.
