### ISSUE TITLE
How can i add http://router.project-osrm.org/viaroute to serviceUrl ?

### ISSUE THREAD

**Issue by CusProjects** [perliedman/leaflet-routing-machine#255]
throws 400 bad request

GET /viaroute/driving/11.96,57.76;11.98,57.68?alternatives=true&steps=true HTTP/1.1
Host: router.project-osrm.org
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8080/
Origin: http://127.0.0.1:8080
Connection: keep-alive

**Comment by perliedman** [comment]
You need to use the legacy OSRM implementation, `L.Routing.OSRM`. From 3.0.0, the default router is `L.Routing.OSRMv1`, which is compatible with OSRM 5.0.

Instatiate your control like this:

```javascript
var control = L.Routing.control({
    router: L.Routing.osrm({...}),
    ...
});
```

Also note that I think OSRM's demo will remove the `viaroute` service in the not so distant future, since it's powered by an old version of OSRM.
