### ISSUE TITLE
Missing js file in `dist` folder on v3.0.2?

### ISSUE THREAD

**Issue by PeterDaveHello** [perliedman/leaflet-routing-machine#268]
Seems there is no js file in version 3.0.2's dist folder, I'm wondering if there is anything wrong in v3.0.2? Thanks.

**Comment by perliedman** [comment]
Ok, that sounds like a problem, but where are you looking?

There are js files on the release tag here: https://github.com/perliedman/leaflet-routing-machine/tree/v3.0.2/dist

Note that I have removed dist files from the main repository, since I believe it is a mistake to have compiled files there, and they are usually out of date anyway.

**Comment by PeterDaveHello** [comment]
Both the commit you bump the version : https://github.com/perliedman/leaflet-routing-machine/tree/780511dfae69607fc1a311e40d4eff404989ee59/dist and the npm package doesn't have the js files.

**Comment by perliedman** [comment]
The bump commit is expected, only the release tag should have the dist files, but I'll have to look into why they're missing from the npm package. Probably won't have time today, though.

**Comment by perliedman** [comment]
Published version 3.0.3 where the NPM package includes the built JS files as earlier. The dist files are available in the Git repo on the release tag, primarily for Bower users; this is the same method that Leaflet uses for dist.

Thanks a lot for reporting and bringing this problem to my attention!

**Comment by PeterDaveHello** [comment]
:+1:
