### ISSUE TITLE
Support for new instructions

### ISSUE THREAD

**Issue by TheMarex** [perliedman/leaflet-routing-machine#285]
Currently LRM does not support instructions of the following types:

- `merge` (left/right)
- `on ramp` / `off ramp`
- `fork` (left/right)

These are common in all supported routing endpoints as such it would be great to include them here.

I just added [support for them on OSM.org](https://github.com/openstreetmap/openstreetmap-website/pull/1261) including icons and would love to see this as well here. (so we could finally include it on our own website maps.project-osrm.org :tada: )

Let me know what you need to get this rolling.

**Comment by perliedman** [comment]
@TheMarex Thanks for giving me a nudge to finally do this!

I've been hesitating to add this since there was no support for adding new localization without actually adding them to for all languages.

I've done some refactoring to try to do this in a backwards compatible way. The current approach will fall back to using english strings if a particular instruction is missing for the current locale.

At the moment, only english and swedish have full support, but it should be pretty straight forward to fix for other languages if you actually know the language :)

**Comment by perliedman** [comment]
@TheMarex when implementing this, I looked at the changes you made for OSM.org for inspiration. 

One thing I noted is that you coerce the modifier for for example `on ramp`/`off ramp` into always being left or right.

For some scenarios OSRM returns the modifier `straight` for these maneuvers, where your code will turn `straight` into `right` - is this intentional and correct? LRM does the same for now.
