### ISSUE TITLE
"osrm is not a function"

### ISSUE THREAD

**Issue by catbadger** [perliedman/leaflet-routing-machine#288]
I need driving distances between points. the following code throws an error.(L.Routing.osrm is not a function) Am I missing something set-up wise?

```
		function calculateDistances( origin, destination){
			var router = L.Routing.osrm();
			var start = new L.Routing.Waypoint(origin.lat, origin.lng);
			var end = new L.Routing.Waypoint(destination.lat, destination.lng);
			var waypoints = [start,end];
			router.route(waypoints, function(err, routes) {
				console.debug(routes[0].summary.totalDistance);
			});
                   }
```

**Comment by perliedman** [comment]
It depends on which version of OSRM you're targeting. For OSRM versions before 5, the code is correct, since it uses `L.Routing.osrm`, which is the old class; however, this class also only works with older versions of Leaflet Routing Machine.

For OSRM 5 and upwards, you should use `L.Routing.osrmv1` instead, which is compatible with OSRM 5's v1 API. This is the router distributed with newer versions of LRM (v3 and up).

The whole version number situation might seem a little confusing, but that's more or less the way it is when software changes and has dependencies on each other, unfortunately. Also sorry about a lot of docs probably still mentioning `L.Routing.osrm` - if you find any specific references to this class, feel free to notify me (or even better, submit a PR to fix!).

**Comment by catbadger** [comment]
Oh this was my bad. I was expecting functions I found elsewhere to work.  Thank you for getting back to me Per!
