### ISSUE TITLE
Request: server ping

### ISSUE THREAD

**Issue by catbadger** [perliedman/leaflet-routing-machine#290]
As the dmeo server for the osrm project sucks, it highlights an issue with the plugin. routingerror does not fire when the server is down. Is it possible to get the server url so that we can ping it before starting to query it? Better yet would be a function is_up() or something of the like.

**Comment by perliedman** [comment]
Hm, could you show what you mean by `routingerror` doesn't fire when the server is down?

Here's the relevant part that should fire the error when a HTTP error occurs: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.OSRMv1.js#L94-97

I've definitely seen that error, although it will sometimes take a lot of time, since the server takes a while to return the error. I think it will be hard to work around that.

**Comment by catbadger** [comment]
see #291

**Comment by perliedman** [comment]
Yes, by default the control will listen to the `routingerror` event and write them to the console (https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Control.js#L39). You can disable it by setting the `defaultErrorHandler`. So logging in the console doesn't necessarily mean an error event isn't fired.

**Comment by catbadger** [comment]
#TIL... thank you!
