### ISSUE TITLE
Long routes without alternative ways

### ISSUE THREAD

**Issue by tevez15** [perliedman/leaflet-routing-machine#331]
Hi

Your plugin is the best, congratulations, but I have some question.

For example, I'm living in Portugal, and when I use waypoints from Lisbon to Faro, he just give me the highway, and for this target, exist the old roads (with one more hour of travel). But if I use some local cities, inside Lisbon, he just give me 2 ways (is the max ways I can get on my tests).

My conclusion, when you pick a long travel, he send the most fast and with less of distance.

PS: For example, we here in Portugal, pay the highways, so many people (like me), goes to other ways, old ways (National roads).

**Comment by perliedman** [comment]
Hi, there glad that you find Leaflet Routing Machine useful!

First, let's make it clear that Leaflet Routing Machine in itself is _just_ a Leaflet control, the actual route calculations are done by some backend - by default, it will use OSRM's demo server. So, the decisions made to produce the route is not done by Leaflet Routing Machine, and actually not something the plugin can change.

Having said that, you are correct when you say that the calculated route is optimized for speed - it will always choose the route that takes the shortest amount of time. To change this, you need to set up your own routing backend; OSRM lets you change the profile it uses, which can make it avoid toll roads, for example. It is however outside the scope of Leaflet Routing Machine.

**Comment by tevez15** [comment]
Thank you for the awnser :)

**Comment by JoaquinBC** [comment]
hi @perliedman,

I am implementing `leaflet-routing-machine` on my website and I find your code very interesting.
I have almost completely migrated to OSM the routes I previously used with Google Maps api, but I lack a detail.

I see that in [OSRM Project](https://github.com/Project-OSRM) the parameters `exclude=motorway`, `exclude=toll` exist since version [5.12.0](https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.12.0), I suppose that to prevent the routes from using motorways / toll roads, but I do not see how to send those parameters with `leaflet-routing-machine`. I guess when you wrote the code they did not exist and that's why you did not take them into account.
How could I use them? Would it be possible for you to add them to the plugin code?

regards

**Comment by perliedman** [comment]
@JoaquinBC you can use the `OSRMv1` router's `requestParameters` for additional HTTP query parameters you want to use, for example set:

`js
{
    exclude: 'motorway'
}
`

You are correct that these options did not exist when I wrote Leaflet Routing Machine, but there are a lot of extension points already that you can probably use.

**Comment by tikky** [comment]
Where exactly should I add mentioned `js { exclude: 'motorway' }`

```
 router: new L.Routing.osrmv1({
    language: 'en',
    profile: 'car',
    **exclude: 'motorway',**
  }),
```

**Comment by perliedman** [comment]
@tikky you should put the `exclude` parameter in the `requestParameters` object:

```js
 router: new L.Routing.osrmv1({
    language: 'en',
    profile: 'car',
    requestParameters: { exclude: 'motorway' }
  }),
```
