### ISSUE TITLE
Arrow direction in route line

### ISSUE THREAD

**Issue by jonatasfreitasv** [perliedman/leaflet-routing-machine#336]
Hi guys!

Exist any way to put arrow in route line to identify route direction ?

Thx.

**Comment by mathisloge** [comment]
https://github.com/makinacorpus/Leaflet.TextPath/tree/leaflet0.8-dev 

`control = L.Routing.control({
  router: router,
  waypoints: waypoints,
  plan: L.Routing.plan(waypoints, {
    createMarker: function(i, wp) {}
  }),
  routeLine: function(route) {
   
    line = L.multiOptionsPolyline(route.coordinates, {
      multiOptions: {
        optionIdxFn: function(latLng) {
         ...
        },
        options: thresholdRoute.colors
      },
      weight: 5,
      lineCap: 'butt',
      opacity: 0.75,
      smoothFactor: 1
    });
   
    line.on('mouseover', function() {
      this.setText('  ►  ', {
        repeat: true,
        attributes: {
          fill: 'red'
        }
      });
    });
    line.on('mouseout', function() {
      this.setText(null);
    });
    return line;
  },
  ....
}).addTo(map);
`

**Comment by perliedman** [comment]
@jonatasfreitasv sorry for not getting back earlier to you on this, but thanks to @mathisloge it looks like this is solved.

I haven't tried Leaflet.TextPath myself, but the code snippet above is in general how I would have done it as well.

Closing this issue for now since I don't think this is something that should go into LRM itself, it's better to make LRM extensible so that you can use other plugins.

**Comment by mathisloge** [comment]
![giphy](https://cloud.githubusercontent.com/assets/13556116/20136566/d7f7deb6-a675-11e6-8d94-171399032f8d.gif)
A running example

**Comment by jonatasfreitasv** [comment]
Thx a lot @mathisloge and @perliedman !!!
