### ISSUE TITLE
Route not in the US

### ISSUE THREAD

**Issue by dajor** [perliedman/leaflet-routing-machine#337]
So when we try to make a route not in the US it does not work. I tried it even on your demo page

**Comment by perliedman** [comment]
This is because OSRM's demo server has some issue at the moment. The demo server is known to not offer any guarantees or SLA, so this is to be expected.

LRM by default uses OSRM's demo server, but you're free to use any OSRM instance that you set up or is provided by someone else. There's also a couple of plugins to use other routing services. For production, you should definitely not rely on the demo server.

This is not an issue with LRM itself, but rather with the backend service it uses by default.
