### ISSUE TITLE
OSRM server is not returning a correct route

### ISSUE THREAD

**Issue by shimchik** [perliedman/leaflet-routing-machine#340]
You can observe this issue on http://www.liedman.net/leaflet-routing-machine/

All routes are incorrect (AZ 95 0 m, 0 s). This is not a leaflet-routing-machine error, but maybe I can get some insight on what to do about it, since it renders the plugin unusable out of the box.

**Comment by slowlyCoder** [comment]
Use your own OSRM Server. You can find more informations here: 
- http://www.liedman.net/leaflet-routing-machine/tutorials/alternative-routers/
- https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

**Comment by perliedman** [comment]
This is because OSRM's demo server is currently broken. It is a known problem, the OSRM team is sorting it out. It's not related to Leaflet Routing Machine itself.

The demo server is free, but comes without SLA or warranties. It often works, but sometimes it doesn't.

If you need better uptime, I suggest paying for a service provider (Mapbox's directions API is built on OSRM and works with LRM out of the box), or setting up your own server, which isn't that hard or expensive if you don't need global coverage.
