### ISSUE TITLE
Center route to the right

### ISSUE THREAD

**Issue by mathisloge** [perliedman/leaflet-routing-machine#344]
Hey, 
is there a way to center the line a little more to the right. 
Now it´s centered. But if you have 2 routes passing each other, you only see one route. 
https://drive.google.com/open?id=0B-a8saE9ykmfNTFVd1dWMk51a2M i hope this link is explaining much more.

**Comment by perliedman** [comment]
Definitely not built into LRM. This is a tricky problem and I don't think there's any ready made library to do this.

A good start could be to read this blog post: https://medium.com/transit-app/how-we-built-the-worlds-prettiest-auto-generated-transit-maps-12d0c6fa502f#.4in2ukqq7 - you don't need to do everything they do, and not on their scale, but it's definitely applicable to what you're trying to achieve.

I'm closing this issue since it's not really something that will be included in LRM, but feel free to post on any progress you make here!
