### ISSUE TITLE
Webpack complaining about pre-built javascript file.

### ISSUE THREAD

**Issue by jakehm** [perliedman/leaflet-routing-machine#347]
I am using webpack and I installed leaflet-routing-machine with npm.
I am getting this warning when I try to compile and run.

```
WARNING in ./~/leaflet-routing-machine/dist/leaflet-routing-machine.js
Critical dependencies:
6:498-505 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/leaflet-routing-machine/dist/leaflet-routing-machine.js 6:498-505

```

**Comment by perliedman** [comment]
Hi Jake,

this is a known effect since the `main` entry in `package.json` actually refers to a browserified UMD bundle. Apparently webpack does not like that.

The change to point to a browserified bundle was made to drop the explicit Leaflet dependency from the plugin, which will cause problems if you just imported the source files with require.

There are probably better ways to work this out, but unfortunately my time to put into this is limited, especially since this particular problem does not affect me (I don't use webpack). Having said that, I would be open to suggestions and PRs to fix this!

**Comment by jakehm** [comment]
What is wrong with an explicit Leaflet dependency?  By making it implicit, people will have to import the same code twice.

**Comment by perliedman** [comment]
The problem with having an explicit dependency is that people can't use the plugin with both Leaflet 0.7 and 1.0, for example: in this case, NPM would be default actually load to different versions, which causes havoc.

Instead, the built dist relies on you having loaded Leaflet and that the global `L` namespace is available - this is actually how most Leaflet plugins work, although it's not the normal way for other NPM modules.

So, it will definitely _not_ cause Leaflet to be loaded twice, Leaflet Routing Machine's dist does not include Leaflet.

NPM had the concept of peer dependencies for this case, which is more or less expliclity targeted towards plugins, but they're somewhat frowned upon, so I have avoided them for now.
