### ISSUE TITLE
No map if waypoints blank

### ISSUE THREAD

**Issue by Rusland3000** [perliedman/leaflet-routing-machine#348]
I want to start map without any Route.
In https://github.com/perliedman/leaflet-routing-machine/archive/v3.2.4.zip in examples\index.js I change:
`var control = L.Routing.control(L.extend(window.lrmConfig, {
	waypoints: [],
...
`
And now map does not loading - http://i.piccy.info/i9/7a323c4e054d44d7ff37291ba8a127ec/1480410457/11772/1079579/blankmap.png

**Comment by perliedman** [comment]
@Rusland3000 since you don't provide any waypoints, no route will be calculated, and the control will not set any map view - there's not way for the control to know what part of the map you want to look at, and there's no reason for it to set the view for you.

You need to call `map.setView` or similar from your code.
