### ISSUE TITLE
More than 2 waypoints

### ISSUE THREAD

**Issue by BasmaNabil** [perliedman/leaflet-routing-machine#375]
Hello,

I have two arrays (AllLat & AllLng) of points for latitude & longitude, i want to assign them to the waypoints to get the shortest route between these points, how can this be done?

Thanks in advance.

**Comment by perliedman** [comment]
Hi,
just pass all the waypoints in the `waypoints` array, as shown in the examples. The plugin supports an arbitrary number of waypoints.

**Comment by BasmaNabil** [comment]
Thanks, i did it
Can you tell me how to clear the route and remove markers in leaflet before adding new one?

**Comment by perliedman** [comment]
Depends a bit on what you want.

Clear route:

```js
control.setWaypoints([]);
```

Remove control:

```js
map.removeControl(control);
```

**Comment by BasmaNabil** [comment]
I tried it but it made the route doesn't appear,am i missing something,here is my code:
var routeControl = L.Routing.control({
         			 }).addTo(mymap);
routeControl.setWaypoints(route);
route=[];
routeControl.setWaypoints([]);

**Comment by perliedman** [comment]
I'm not sure what you're trying to achieve with that code, but since routing is done asynchronously, it will most likely not do what you hope it will do.

You're first making a routing request with the waypoints from `route`, which you're then immediately clearing and replacing with an empty waypoint list, before the routing result has returned or been shown.

I would suggest familiarizing yourself with asynchronous code and events in JavaScript. I would think you would only do `routeControl.setWaypoints([])` in an event handler or similar.

**Comment by BasmaNabil** [comment]
Thanks alot, i found my mistake :)

**Comment by BasmaNabil** [comment]
Thanks alot...i found my mistake :)

**Comment by tenznhok** [comment]
I have about 1000 points, and as soon as I add them into the waypoints, it doesnt seem to draw the route anymore. Any help or suggestion?

**Comment by perliedman** [comment]
@tenznhok 1000 waypoints is _way_ beyond what you should use Leaflet Routing Machine. LRM is a UI for creating routes, and I assume you would not attempt to create a route with 1000 waypoints in for example Google Maps?

Just guessing, but are you really trying to do map matching against a GPS trace or similar? You should use OSRM's match functionality for this.

Also, for datasets of this size, you should use your own OSRM server (you should always do that for production use anyway); I think the demo server is capped to 100 points or something like that.

**Comment by rks-0110** [comment]
@BasmaNabil could you share how you solved this problem? I'm running into a similar problem.

**Comment by curtisy1** [comment]
> `L.latLng(allLat, allLng)`

What you're trying to do cannot work and is inherently different from `L.latLng(allLat[1],allLng[1])`. This is because the `LatLng` object in Leaflet (and in general) works on a _latitude_ and a _longitude_ (and an altitude, if you pass a third parameter). However in the code above, you pass an _array_ of latitudes and longitudes into the constructor, so Leaflet does nothing with it and you get no waypoints.

What you should do instead is pass your array of lats and lngs as waypoints
```js
const allLat = [a, b, c];
const allLng = [x, y, z];
L.Routing.control({
    waypoints:[
        L.latLng(a, x),
        L.latLng(b, y),
        L.latLng(c, z),
    ],
}).addTo(map);
```

or
```js
const allLat = [a, b, c];
const allLng = [x, y, z];
L.Routing.control({
    waypoints: allLat.map((l, i) => L.latlng(l, allLng[i]),
}).addTo(map);
```

if you have n potential waypoints

**Comment by rks-0110** [comment]
Thx that was great help
