### ISSUE TITLE
CreateMarker is not working

### ISSUE THREAD

**Issue by BasmaNabil** [perliedman/leaflet-routing-machine#384]
I am making a route between some points and i want to change the blue markers that appeared for the start & end points but doesn't changed,and also i want to change the size of the control as it overlap with the legend in the map.

routeControl = L.Routing.control({
		createMarker: function() { return null; },
		collapsible: true,
		lineOptions: {
			      styles: [{color: 'red', opacity: 1, weight: 3}]
			   },
		routeWhileDragging: true
           	 }).addTo(mymap);
		routeControl.setWaypoints(route);

**Comment by perliedman** [comment]
Hi,
not sure exactly where the problem lies, but this works for me. See a running example of your code here: http://playground-leaflet.rhcloud.com/wobu/edit?html,output - as you can see, markers have been disabled.

Regarding height of container, overriding the CSS styles is the only option at the moment.
