### ISSUE TITLE
Language Problem on v3.2.5

### ISSUE THREAD

**Issue by andrealemanno** [perliedman/leaflet-routing-machine#411]
Hi everyone,
i updated to LRM v3.2.5 and my language choice doesn't work anymore. 
I create my control like this:

var newControl = L.Routing.control({
        waypoints: WAYPOINTS,
        router: actualRouter,
        fitSelectedRoutes: "smart",
        formatter: formatter,
        show: true,
        routeWhileDragging: false,
        useZoomParameter: true,
        language: 'it'
    });

myMap.addControl(newControl);

It use to work on v3.2.4 and show instruction in italian but now with 3.2.5 i see instruction in english. There can be the possibilities that there is a small bug in the new version or am i doing something wrong?
Thanks in advance for your help.
Best regards

Andrea

**Comment by perliedman** [comment]
The explanation is that from 3.2.4 to 3.2.5, localization changed from being handled internally, to using the [`osrm-text-instructions`](https://github.com/Project-OSRM/osrm-text-instructions/) module, so that we can rely on a database that is likely to be better maintained.

In retrospect, this change should probably have been indicated with more than just a patch version change, especially since this means some languages that were previously supported might not longer be, if they're missing from `osrm-text-instructions`. Sorry about that.

It's been a while since we upgraded version of `osrm-text-instructions`, maybe they have italian support now? Otherwise, it would probably be great to step up and contribute such support.

Meanwhile, the obvious workaround is to continue using 3.2.4.

**Comment by emmexx** [comment]
Can you please give us some more information about osrm-text-instructions.
I'm not sure how that module is to be added to lrm. In leaflet-routing-machine.js I found references to osrm-text-instructions and translations to a bunch of languages.
osrm-text-instructions must be packaged together with lrm or it has to be added as a separate file?

**Comment by perliedman** [comment]
@emmexx it's bundled with LRM if you use the pre-built files. If you include LRM in your build using CommonJS, LRM has it listed as a dependency.

**Comment by emmexx** [comment]
Ok. Now Osrm-text-instructions has the italian translation, I'll wait for 3.2.6

**Comment by wangzi6578** [comment]
hello,
i have set up osrm demo server. and i already have the respond json from match service,so,how could i use the lrm draw this ponits in demo web,

**Comment by Khorda** [comment]
Hello @perliedman ,
I'm having problems with instructions localization using osrm. I tried different languages codes (used 'language' parameter while creating a control through L.Routing.control, such as  'de', 'es' and 'it'), but none of them seems to work because I always get english instructions back.

I am using 3.2.7.

Is this a bug or my ignorance?

Thanks

**Comment by perliedman** [comment]
@Khorda hm, without seeing code, I'm guessing is weird on your end. Look at this simple example, where german ("de") works: https://plnkr.co/edit/sBPWYYMo08ijyQ6NxO0n?p=preview

**Comment by curtisy1** [comment]
Closing as this seems to be resolved
