### ISSUE TITLE
Remove hover event from the instructions text

### ISSUE THREAD

**Issue by PriyeshT** [perliedman/leaflet-routing-machine#412]
Hello,

Thanks for the great plugin @perliedman . 

_Following is not an issue with the plugin itself._

I have extended the plugin to support the Singapore governments One Map 2.0 API for Multi-point routing. I get the instructions text from the One Map 2.0 API. The API does not return geometry for individual instructions, instead returns geometry for the entire route. 

So whenever I hover on the instructions text I get the following error:

> Uncaught TypeError: Cannot read property 'lat' of undefined

Is there a way we can disable the hover event for the instructions text or the instructions container?

Thanks,
Priyesh T.

**Comment by perliedman** [comment]
Hi, great to hear that you're extending Leaflet Routing Machine and finding it useful.

From a brief look, I don't think there's anything like that in the code. However, it would probably be a good idea to make `Instruction`'s `index` property optional, so that it could be left out, and just don't add the hover feature for those instructions.

I think this would be very straight forward, just adding a conditional to check that `index` is set around this line: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/itinerary.js#L154

I would be happy to merge a pull request for this feature!

**Comment by PriyeshT** [comment]
Hello,

Thanks for the suggestion. Your suggestion worked for my case. 

The instructions which I get have a coordinate associated with it. And I get the list of coordinates to draw the polyline from route geometry.

I added 'index' property to the instruction object and passed it to the 'coordinates' object. But the coordinates for the instruction and the coordinates for the corresponding index in the 'coordinates object' were not same. And hence I was not getting the desired results. 

I am now passing the coordinate from the individual instruction and calling 

> this._addRowListeners(step, r.coordinates[instr.index]);

with the coordinate instead of the instruction index. This works for my scenario.

I wanted to bring this up before making the change to the plugin. 

Currently, I have modified the plugin as below: 

> if(instr.index) {
this._addRowListeners(step, r.coordinates[instr.index]);
} else {
this._addRowListeners(step, instr.coordinate);
}

I am not sure if the else condition would be useful others who use the plugin. 

Let me know, if i should go ahead add only the if condition.

**Comment by perliedman** [comment]
Hm, interesting. Yes, that looks like a good solution in your case.

However, as you say, I don't think it's a very common case for other routers (or at least I haven't seen it before), so I think a good solution for the plugin would be to _just_ add then conditional, as you say.
