### ISSUE TITLE
How to Use osrm text instructions

### ISSUE THREAD

**Issue by brygom** [perliedman/leaflet-routing-machine#431]
Hello, exist some documentation about osrm text instructions ? I already trying look directly in osrm text instructions but I can'f found something util. 

Thank you

**Comment by perliedman** [comment]
Since the last versions, Leaflet Routing Machine will by default use `osrm-text-instructions` to create the instructions, so you should be good to go, if that is all you want.

If you want to customize, you can also supply the `stepToText` option when creating the `OSRMv1` instance; you can send a function that takes a [RouteStep](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#routestep-object) object as argument, and should return a string of text.
