### ISSUE TITLE
Disabling logging w/ OSRMv1

### ISSUE THREAD

**Issue by floriansimon1** [perliedman/leaflet-routing-machine#437]
Hello,

Inside the dist files, I noticed there is a `console.log` that outputs the following:
```
Encountered unknown instruction type: exit roundabout
Encountered unknown instruction type: exit rotary
Encountered unknown instruction type: exit roundabout
```

It's fine and all, but I couldn't care less. My routes are displayed and that's all I care about. I would like to make this "disable-able", but if I submit a pull request, will you accept it? I'd like to avoid wasting my time if there is no chance that you accept changing this.

**Comment by perliedman** [comment]
Hi, this log output is not from Leaflet Routing Machine, but possibly from `osrm-text-instructions`, that is used by Leaflet Routing Machine. Probably because your OSRM server responds with instructions unknown to the current version of `osrm-text-instructions`. Upgrading should probably fix this.

Closing, since this is not a LRM issue as far as I can tell!
