### ISSUE TITLE
LRM + Match API

### ISSUE THREAD

**Issue by hellracer** [perliedman/leaflet-routing-machine#438]
Hi Per,

Any chances that LRM will support match api on OSRM? or create a separate project?

**Comment by perliedman** [comment]
Hi!

My gut feeling is that map matching is somewhat specialized and also not a very frequent use case. I would probably suggest doing this as a separate project, although I would be happy to discuss the possibility to share functionality or build such a project as a plugin to LRM.

How do you envision map matching working?

**Comment by hellracer** [comment]
Hi Per,

To be honest, I don't have the technical capability to determine the proper scope of the project because I don't have prior experience with the internals of OSRM, but what I do know is on the a user level perspective the plugin should be comparable how mapzen and graph hopper do their match api . Actually if we can afford your service that's the place to start :)

**Comment by perliedman** [comment]
Hi again,
to me it feels like the match functionality and the route functionality is two quite different use cases from a UI point of view, even though OSRM offers services for both. By that, I mean that I don't think there would be much point in adding match functionality to LRM, since it wouldn't share much code with the already existing UI for routing.

It would probably be better to build a new module for matching, although I'm not certain how general such a plugin could be - matching in general is a much more specialized task than routing.

Having said that, feel free to contact me privately (per@liedman.net) if you would be interested in some help with building something like that.

I'm closing this issue for now, since I don't think there's much more to do within the LRM project.
