### ISSUE TITLE
change route style within segments

### ISSUE THREAD

**Issue by MichalPP** [perliedman/leaflet-routing-machine#449]
how do I change displayed route style based on parameters? 

I would like to display step/segment part of the line with color dependent on the speed of the segment (eg below 50 km/h -> red, above 50 km/h green). or based on the mode (eg bicycling -> green, pushing bike -> red). 

so far I've only found solutions to change color of the whole line, not segments only.

**Comment by perliedman** [comment]
@MichalPP there's no built-in solution for this, sorry.

Your best bet is probably to extend the `L.Routing.Line` class and make it style as you want, and then use the routing control's `routeLine` option (see options for [`L.Routing.Control`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control))to make it use your implementation instead of the default.

**Comment by MichalPP** [comment]
@perliedman could we make this open? with feature request tag. hopefully someone will stumble upon this.

**Comment by zeeuss** [comment]
Hi MichalPP! How did you solve it?

**Comment by MichalPP** [comment]
I did not (my knowledge of JS is very limited). [here is](https://www.freemap.sk/?map=17/48.149560/17.123061&layers=X&tool=route-planner&points=48.150254/17.115390,48.149954/17.128973&transport=bike) an implementation or a possible visuaization.

**Comment by AmduX64** [comment]
Has there been any update regarding this?

**Comment by curtisy1** [comment]
Not really. As of now, the only solution is the one mentioned [above](https://github.com/perliedman/leaflet-routing-machine/issues/449#issuecomment-350971113)
