### ISSUE TITLE
Unable to mix draggable and non-draggable waypoints

### ISSUE THREAD

**Issue by buswizard** [perliedman/leaflet-routing-machine#457]
I am trying to achieve a mixture of draggable and non-draggable waypoints in a single route by using 

```
L.marker(
    wp.latLng,
    { icon: <change_icon_if_waypoint_was_added_by_user> }, 
    { draggable: <true_if_waypoint_was_added_by_user> }
);
```
in my

`L.Routing.control({ createMarker: function() })`:

The icon changes as expected, but all waypoints are non-draggable when rendered in the UI.

Is this a bug, or is such a mixture not supported?

**Comment by perliedman** [comment]
Hi, as long as you have `draggableWaypoints` set to `true` (the default), I think you should be able to turn this feature on or off for individual waypoints like you do in your example.

To verify this, I threw together this small example: https://plnkr.co/edit/2jVyS7hl9K1CJUEvgwNf?p=preview

As you can see, the first waypoint isn't draggable, while the second is draggable.

Please share some code if it turns out this is still an issue for you.

**Comment by buswizard** [comment]
Thank you. The problem was a javascript error in my code. I should have been using:
```
L.marker(
    wp.latLng, {
        icon: <change_icon_if_waypoint_was_added_by_user>, 
        draggable: <true_if_waypoint_was_added_by_user>
    }
);
```
