### ISSUE TITLE
Add waypointclick event

### ISSUE THREAD

**Issue by david-k** [perliedman/leaflet-routing-machine#466]
Hi,
as I see it, there are currently events for `waypointdragstart`, `waypointdrag` and `waypointdragend`. What I would need is `waypointclick` to show some information when the user clicks on a waypoint. Any chance this could be added?

**Comment by perliedman** [comment]
`waypointdragstart` etc. are used internally to track dragging, that's why those events exist.

If you need to add custom events to the waypoint markers, you are better off using the `createMarker` option to control how the markers are created. That way, you can change icons, add any events you need, etc.

Hope this helps!

**Comment by david-k** [comment]
Thank you, missed that option!
