### ISSUE TITLE
Languages other than 'en' do not work since version 3.2.5

### ISSUE THREAD

**Issue by davicustodio** [perliedman/leaflet-routing-machine#474]
Hello, first of all I would like to congratulate and thank you for working with the plugin.
In some tests I've been doing, I've come to realize that no language (other than English) is running from version 3.2.5.
I'm using version 3.2.8, and I already tried to use language: 'it', language: 'de', language'pt ', but any of them the plugin ignores and mounts the text of the routes in English.
I was reading Issue #411 and then tried to update the version of osrm-text-instructions, but still the languages ​​are still being ignored.
I tried using pt-BR (which is available in the list of languages ​​available in osrm-text-instructions), but I get an error saying it is not a valid language.
I also tried to insert a 'pt-BR' session in Localization (copying the 'pt' session), but it still did not work.
However, when returning to version 3.2.4, the it, de, and pt languages ​​come back to work. (the pt-BR which is my case, does not work even in 3.2.4).

Is there any quick hint, before the issue is officially resolved, for me to solve this problem in the code, and run the pt-BR available in osm-text-instructions?

Thanks for listening.

**Comment by yuryleb** [comment]
Actually if I set `ru` language in https://github.com/perliedman/leaflet-routing-machine/blob/master/examples/localized.js#L12 and run [localized.html](https://github.com/perliedman/leaflet-routing-machine/blob/master/examples/localized.html) sample in browser, I got all properly localized steps and even with Russian grammar rules support introduced in OSRM Text Instructions since 0.8.0 (2017-10-04). Did you run `npm install` to get updated osrm-text-instructions package?

**Comment by perliedman** [comment]
Sorry for not getting back to you on this before. I have attempted a fix for this in the newly released version 3.2.9.
