### ISSUE TITLE
Own server vs Demo server, almost same request, different behavior

### ISSUE THREAD

**Issue by Dada2201** [perliedman/leaflet-routing-machine#475]
Hi,
I've just set up my own server of osrm and i got this issue, the routing between the demo server and mine is different.

Here is my server request : 
`http://192.168.140.184:5000/route/v1/car/0.126062,49.4919;0.26524,49.4069;0.25897,49.4085;0.248082,49.411;0.237784,49.4186;0.2304,49.4167;0.227958,49.4131;0.211738,49.3963;0.209462,49.3942;0.204832,49.384;0.185685,49.3482;0.158007,49.3607;0.130618,49.3823;0.127812,49.3727;0.104102,49.3454;0.098423,49.3491;0.08374,49.3594;0.073568,49.3572;0.068683,49.3553;0.060987,49.3526;0.050532,49.3488;0.039535,49.3442;0.027902,49.3386;0.006378,49.3276;-0.006702,49.3205;-0.012588,49.3129;-0.02787,49.3068;-0.063563,49.2977;-0.07364,49.3004;-0.084745,49.2991;-0.09235,49.2934;-0.10123,49.2877;-0.107133,49.287;-0.114488,49.2866;-0.124378,49.2875;-0.133657,49.2863;-0.138603,49.2856;-0.144483,49.2849;-0.160745,49.2847;-0.189303,49.2835;-0.196085,49.2814;-0.205812,49.2777;-0.230148,49.2633;-0.23092,49.256;-0.231052,49.2519;-0.233617,49.2473;-0.233958,49.2441;-0.22626,49.2404;-0.253523,49.2315;-0.245243,49.2195;-0.271945,49.2104;-0.29412,49.1982;-0.31105,49.1856;-0.320742,49.18;-0.328757,49.1774;-0.33608,49.1753;-0.34607,49.1768?overview=false&alternatives=true&steps=true&hints=;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;`

Here is the demo server one : 
`https://router.project-osrm.org/route/v1/driving/0.2338889,49.4197222;0.1079732,49.4938975?overview=false&alternatives=true&steps=true&hints=Y9E1ghJptYgAAAAAJgAAAAUBAAAAAAAAAAAAAPYG3kBSQjxCAAAAAAAAAAATAAAAggAAAAAAAABL7AAA9JEDAJsV8gKhkQMAyhXyAgIA7wcx-p3a;H_0jgP___39UAAAALQAAAHECAAAAAAAA6Dk9QTfmskCMBq5CAAAAAFQAAAAWAAAAcQIAAAAAAABL7AAAAKYBAHk68wLFpQEAijfzAgMADxEx-p3a`

![demorequest](https://user-images.githubusercontent.com/26485142/40051054-a776a106-5839-11e8-9e10-c5dee775fc6a.PNG)

![ownrequest](https://user-images.githubusercontent.com/26485142/40051060-ac627348-5839-11e8-9198-126738b7ccc7.PNG)

I don't want this grey line, it's surely an option that I missed.
Any thoughts?

**Comment by perliedman** [comment]
Hi!

The grey line indicates that the routing engine did not give an answer on how to get from the first waypoint to the first point on the red line.

When OSRM can't find a routable point exactly where the first waypoint is, it will instead find the closest point available in its network, and route from there.

Most of the time, you don't even realize this is happening, since the snapped point is very close to the original waypoint, but in your case it ends up very far from the original point.

It looks like there must be some difference between you routing data and the demo servers data that cause this.

If you just want to remove the grey line, you can use the option [`waypointMode`](http://www.liedman.net/leaflet-routing-machine/api/#l-routing-control) and set it to `snap` instead of `connect` (which is the default).

**Comment by Dada2201** [comment]
So i changed waypointMode to snap. 
It do not correspond to my expectations :disappointed: .

![changed](https://user-images.githubusercontent.com/26485142/40053531-e71017cc-5841-11e8-8695-20e4e4e78e75.PNG)

There is no way to get the same result as the first picture without changing data ?

**Comment by Dada2201** [comment]
Or maybe i can edit lua car profile to avoid something ? This might force routing on road ?

**Comment by perliedman** [comment]
Sorry, exactly why your server responds differently is impossible for me to say, since I don't know how your server is set up. LRM only displays whatever the server responds with. So something is different between your server and the OSRM demo server, possibly different geographic area cover.

From what I can tell, this is not an issue with LRM, so I'm going to close this for now. Feel free to add more info if you believe this is an issue with LRM rather than OSRM or your server setup.
