### ISSUE TITLE
Bug in routing for Address in Netherlands

### ISSUE THREAD

**Issue by apfz** [perliedman/leaflet-routing-machine#478]
Find attached two screenshots. 

From Location A (Brugstraat 16-5, Arnhem, Netherlands) to Location B (Meijnerswijk 13) gives an incorrect route while from A to Meijnerswijk 12 gives the correct one. Seems that in case of door number 13, the nearest road is snapped to the one across the river.  

<img width="1146" alt="correct" src="https://user-images.githubusercontent.com/4879264/40966181-1281a398-68b0-11e8-964f-ff5442326c32.png">
<img width="1169" alt="incorrect" src="https://user-images.githubusercontent.com/4879264/40966182-12a48b9c-68b0-11e8-903f-60f2b0126326.png">

**Comment by perliedman** [comment]
Hi!

As I understand it, this is not an issue with Leaflet Routing Machine, but rather with OSRM or the underlying OpenStreetMap data. Snapping is not done in Leaflet Routing Machine, but in the routing backend (which by default is OSRM).

From a quick look, it looks like OSRM for some reason thinks the "Meijnerswijk" road is not routable, which makes the road on the other side of the channel the only option.

Look at the in OpenStreetMap, and possibly contact the OSRM team if you still believe this is an issue with the software rather than the geographic information.
