### ISSUE TITLE
Property-Routing-does-not-exist-on-type-typeof-import

### ISSUE THREAD

**Issue by Lweaver5051** [perliedman/leaflet-routing-machine#490]
I'm new to leaftlet and need so help understanding what I'n doing wrong, I believe I've added everything needed to use the Leaflet Routing Machine API but clearly I'm missing something because I get a error on Leaflet.Routing.control.  Property 'Routing' does not exist on type 'typeof import("node_modules/@types/leaflet/index")'. Thank you in advance for your help

I did added these refs and scripts as the documents said: 

import L from 'leaflet';

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" />
    <link rel="stylesheet" href="../dist/leaflet-routing-machine.css" />
	<script src="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js"></script>
  <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
  <script src="../dist/leaflet-routing-machine.js"></script>

**Comment by perliedman** [comment]
It sounds like the issue is that you are loading multiple instances of Leaflet, and then Leaflet Routing Machine attaches itself to the wrong instance.

When using `imports`, they can not be mixed with `script` tags, or at least, you need some luck to get that working. The best in your scenario is probably to stick only using `import`s: import Leaflet and the import Leaflet Routing Machine. That way, Leaflet Routing Machine will attach to the same Leaflet as you are importing, unless something really funny is going on.

Hope this helps.
