### ISSUE TITLE
OSRMv1 show HTTP request failed: undefined

### ISSUE THREAD

**Issue by SuperPat45** [perliedman/leaflet-routing-machine#510]
Hi,
OSRMv1 show error HTTP request failed: undefined when too many request whereas a better error message is returned in the response.

When error, If the returned JSON text contains a "message" key, its content should be shown instead "undefined"

**Comment by perliedman** [comment]
If I understand what you report correctly, you are referring to the HTTP 429 errors that the demo server frequently return. As much as I would love to show a better error message, this was impossible last time I checked, since the demo server does not set the correct CORS headers on 429 errors, so the error response is opaque to the the script.

If I misunderstood the issue, please add an example of the request you think should be handled differently, I will try to see what we can do.

**Comment by SuperPat45** [comment]
The HTTP 429 errors return the header:

> access-control-allow-origin: *

![sans titre](https://user-images.githubusercontent.com/7791600/53002515-2460b100-342d-11e9-8259-7b0864439078.png)
And the content is:
`{"message":"Too Many Requests"}`

So the patch works fine: https://github.com/perliedman/leaflet-routing-machine/pull/511

**Comment by perliedman** [comment]
Ok, this is obviously something they improved since last time I checked, thanks for the heads up! :+1:

**Comment by GerfriedC** [comment]
can this behavior be explained, even if using the URL delivers a result from the routing server?
Routing error: 
message: "HTTP request failed: undefined"
"https://router.project-osrm.org/route/v1/driving/14.5480409,47.4910077;14.2913472,48.2909995?overview=false&alternatives=true&steps=true&hints=;"
