### ISSUE TITLE
Wrong type definition in route method callback

### ISSUE THREAD

**Issue by samirbraga** [perliedman/leaflet-routing-machine#562]
Hi, I have noted that the method `route` of class `OSRMv1` has a parameter called `callback` typed as `(args?: any) => void`, but the callback expects an error as the first argument and routes as second. The code follows:

```ts
class OSRMv1 implements IRouter {
    constructor(options?: OSRMOptions);

    route(waypoints: Waypoint[], callback: (args?: any) => void, context?: {}, options?: RoutingOptions): void ;
    buildRouteUrl(waypoints: Waypoint[], options: RoutingOptions): string;
}
```
The typescript compiler raise an exception and the only way I made it work was:
```ts

router.route(waypoints, function () {
    const routes = [arguments[1]];
    ...
```

**Comment by perliedman** [comment]
Hi! Thanks for giving a heads up. Unfortunately, I am not responsible for the TypeScript definitions for this library, and they are not a part of the library itself. Since I don't personally use TypeScript, I am not even sure how it works our how the definitions are maintained, but I hope you can figure it out!
