### ISSUE TITLE
how to get all the distances from point 1 to point 2 to the destination

### ISSUE THREAD

**Issue by elangabdulazis** [perliedman/leaflet-routing-machine#646]
hi
I want to ask if there is a distance calculation using a leaflet?
because I need distance data from latitude 1,2,3 to finish

**Comment by curtisy1** [comment]
The plugin itself does not perform any distance calculation. The distance between the waypoints is returned by the respective routing api (i.e. [OSRM](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#example-response-1)).

If you just need the distance between two LatLngs, you could use Leaflet's builtin [distanceTo](https://leafletjs.com/reference.html#latlng-distanceto) function

**Comment by elangabdulazis** [comment]
can i apply a* algorithm to route finding in leaflet?

**Comment by curtisy1** [comment]
Not sure I get the question. Is it that you want to use your own routing provider? The plugin itself only uses different backend services and formats the returned waypoints. So if you want different results, you would either have to use a different routing provider or build your own (see [osrmv1 for reference](https://github.com/perliedman/leaflet-routing-machine/blob/master/src/osrm-v1.js#L56))

It would also help if you could share some code or runnable example, so I can understand what exactly is going on

**Comment by elangabdulazis** [comment]
I also want to ask how in the leaflet to get distance data?

**Comment by elangabdulazis** [comment]
I also want to ask how in the leaflet to get distance data?

**Comment by curtisy1** [comment]
See my [first reply](https://github.com/perliedman/leaflet-routing-machine/issues/646#issuecomment-983009576) on how to use distanceTo for getting the distance between two LatLngs.

All this plugin does is request the distance data from an API of your choice and format it accordingly.
It does not do any distance calculation itself.

If that is not your issue, please provide a code snippet or codesandbox/etc. that shows how your question is related to leaflet-routing-machine. Otherwise I can't accurately help you.

**Comment by tmbp95** [comment]
Hello all, I'm not sure if this is the right place to question this, but I believe it kinda relates so, here it is:
Is there a method to access the private object _selectedRoute? I'm trying to get the summary from it because I will need to get the distance and duration of the selected route. 

Thank you,
Best regards

**Comment by curtisy1** [comment]
@elangabdulazis @tmbp95 Can I go ahead and mark this question as resolved?

**Comment by tmbp95** [comment]
Yes, thank you!
