### ISSUE TITLE
Custom localization

### ISSUE THREAD

**Issue by 2803media** [perliedman/leaflet-routing-machine#78]
Hi,

I wonder how I can pass custom language to the L.Routing.control like 'language: 'fr'' 
If you have a quick example it will be very helpful thanks in advance, best

**Comment by perliedman** [comment]
Hi,
have a look at `L.Routing.Localization.js`: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/L.Routing.Localization.js

It's basically just a hash with the language code as key. See the existing examples on what you need to provide (basically, just copy an existing localization and replace with the texts in your language).

Since JavaScript is the way it is, you can just add your localization to the `L.Routing.Localization` object, and you're all set, just create a routing control with the option `language: 'fr'`, or whatever.

On a side note, once you've made a localization, you're more than welcome to submit a pull request, so we can extend language support in Lealfet Routing Machine.

**Comment by 2803media** [comment]
Hi thanks for your reply.

Still new to pull request so if you want to add the localization for french here is the code:

        'fr': {
			directions: {
				N: 'nord',
				NE: 'nord-est',
				E: 'est',
				SE: 'sud-est',
				S: 'sud',
				SW: 'sud-ouest',
				W: 'ouest',
				NW: 'nord-ouest'
			},
			instructions: {
				// instruction, postfix if the road is named
				'Head':
					['Tout droit au {dir}', ' sur {road}'],
				'Continue':
					['Continuer au {dir}', ' sur {road}'],
				'SlightRight':
					['Légèrement à droite', ' sur {road}'],
				'Right':
					['A droite', ' sur {road}'],
				'SharpRight':
					['Complètement à droite', ' sur {road}'],
				'TurnAround':
					['Faire demi-tour'],
				'SharpLeft':
					['Complètement à gauche', ' sur {road}'],
				'Left':
					['A gauche', ' sur {road}'],
				'SlightLeft':
					['Légèrement à gauche', ' sur {road}'],
				'WaypointReached':
					['Point d\'étape atteint'],
				'Roundabout':
					['Au rond-point, prennez la sortie {exitStr}'],
				'DestinationReached':
					['Destination atteinte'],
			},
			formatOrder: function(n) {
				return n + 'º';
			}
		}
