### ISSUE TITLE
serviceUrl option need http prefix for telerik simulator

### ISSUE THREAD

**Issue by Qberon** [perliedman/leaflet-routing-machine#90]
Excellent job! Great plugin! 

Small issue.

Without "http:" prefix in serviceUrl option leaflet-routing-machine can't grant access to this server in Telerik Simulator cause script try connect to local service. 

After replace
//router.project-osrm.org/viaroute
to 
http://router.project-osrm.org/viaroute
all works perfect

Thanks again! Very easy implement elegant plugin!

**Comment by perliedman** [comment]
Hi, and thanks, nice that you find the plugin useful.

The issue with the protocol relative URLs comes up every now and then, since they can't be used from `file://` and some other tools.

Since `https` support is kind of important, I think defaulting to `http` is a no-go, but maybe we could just always use `https`, as I can't really see a downside with that.

**Comment by curtisy1** [comment]
Closing as the serviceUrl options now defaults to `https` for all router implementations
