### ISSUE TITLE
Dodge polygons

### ISSUE THREAD

**Issue by jmgarciamari** [perliedman/leaflet-routing-machine#94]
Hi!, I have a geojson loaded in a map, I want to make routes but I need to dodge polygons (closed streets), Is there any way ?

Thanks a lot

**Comment by perliedman** [comment]
Since the actual routing calculation is done by the backend (by default, OSRM), there's no easy way to do this client side.

You could maybe insert via points to try to route around your polygon, but that is no guarantee it will actually avoid the area in question.

Do the restricted areas change frequently? Otherwise, you can probably set up your own OSRM instance and remove the streets in question from the routing data (this is easier than you might think, OSRM is quite a breeze to setup and configure).

**Comment by drmonty** [comment]
I was having a similar issue and ended up in using [TomTom Online Routing](http://developer.tomtom.com/products/onlinenavigation/onlinerouting) as backend, which provides for all waypoints a route so far.

Created a [backend](https://github.com/drmonty/lrm-tomtom) for leaflet-routing-machine based on lrm-graphhopper yesterday.

**Comment by perliedman** [comment]
@drmonty wow, nice work! I'd be happy to link to your plugin from the LRM site if you want.

**Comment by drmonty** [comment]
@perliedman sure, that would be great :smile:
