### ISSUE TITLE
NS_ERROR_DOM_BAD_URI: Access to restricted URI denied

### ISSUE THREAD

**Issue by pmcgrath1** [perliedman/leaflet-routing-machine#95]
I am getting this error when I am trying to run the basic tutorial, any suggestions ?

**Comment by perliedman** [comment]
Are you trying to run the example using a `file://` URL?

That does not work, since the OSRM server URL uses a protocol relative URL. Please serve the example through an HTTP server. (I recommend NPM's [http-server](https://www.npmjs.com/package/http-server) - install it globally and you can set up a static HTTP server anywhere in absolutely no time and with no fuss.)

**Comment by pmcgrath1** [comment]
Ok thanks, I will be using this in a phonegap app, I was just testing it locally first.

**Comment by moimael** [comment]
That is problematic, for example when developing with FirefoxOS simulator.

**Comment by perliedman** [comment]
Using the `serviceUrl` option, you can set the URL to anything you like!

Having said that, it would probably be a good idea to just always use `https`.

**Comment by Kcchouette** [comment]
It's a good idea to put ```https``` so you can use it withou HTTP Server.

Else just modify https://github.com/perliedman/leaflet-routing-machine/blob/3c351754f61d947120b3272ae894bde9064eb1f6/dist/leaflet-routing-machine.js#L1924 to ```serviceUrl: 'https://router.project-osrm.org/viaroute',```
